FROM ubuntu:latest

# Ustawienie strefy czasowej i konfiguracja tzdata
RUN ln -fs /usr/share/zoneinfo/Europe/Warsaw /etc/localtime && \
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y tzdata && \
    dpkg-reconfigure --frontend noninteractive tzdata

ENV TZ="Europe/Warsaw"

# Kopiowanie aplikacji do obrazu
COPY . /app
WORKDIR /app

# Instalacja zależności
RUN apt-get update && \
    apt-get install -y \
    libmpd-dev \
    curl \
    libcurl4-openssl-dev \
    libmpdclient-dev \
    libmosquitto-dev \
    libi2c-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN chmod +x /app/start.sh

# Otwieranie portów
EXPOSE 48833/udp
EXPOSE 48833/tcp

# Ustawienie punktu wejścia
ENTRYPOINT ["/app/start.sh"]
