TEMPLATE = app
CONFIG += console c++14
CONFIG -= app_bundle
CONFIG -= qt
QMAKE_CXXFLAGS += -O3   -std=c++14 -DNOSSL
LIBS +=   -L/usr/local/lib -lgtest -lgtest_main  -lwiringPiDev -lwiringPi -llirc_client   -lrt -lpthread  -lcurl  -lmpd

SOURCES += main.cpp \
    ../../libs/useful/usefull.cpp \
    idomtools_mpd.cpp \
    idomtools.cpp \
    ../433MHz/rc_433mhz.cpp \
    ../blockQueue/blockqueue.cpp \
    ../c_connection/c_connection.cpp \
    ../c_connection/c_connection2.cpp \
    ../c_connection/c_connection_node.cpp \
    ../c_irda_logic/c_irda_logic.cpp \
    ../c_master_irda/master_irda.cpp \
    ../command/commandClass/command_433mhz.cpp \
    ../command/commandClass/command_ardu.cpp \
    ../command/commandClass/command_big.cpp \
    ../command/commandClass/command_clock.cpp \
    ../command/commandClass/command_cmd.cpp \
    ../command/commandClass/command_event.cpp \
    ../command/commandClass/command_hello.cpp \
    ../command/commandClass/command_help.cpp \
    ../command/commandClass/command_idom.cpp \
    ../command/commandClass/command_ip.cpp \
    ../command/commandClass/command_log.cpp \
    ../command/commandClass/command_mpd.cpp \
    ../command/commandClass/command_ok.cpp \
    ../command/commandClass/command_put.cpp \
    ../command/commandClass/command_show.cpp \
    ../command/commandClass/command_sleep.cpp \
    ../command/commandClass/command_state.cpp \
    ../command/commandClass/command_stop.cpp \
    ../command/commandClass/command_uptime.cpp \
    ../command/commandClass/commandexit.cpp \
    ../command/commandClass/commandrs232.cpp \
    ../command/commandClass/commandtest.cpp \
    ../command/command.cpp \
    ../command/commandhandler.cpp \
    ../command/commandhandlerroot.cpp \
    ../command/commandhandlerrs232.cpp \
    ../CRON/cron.cpp \
    ../files_tree/files_tree.cpp \
    ../files_tree/main.cpp \
    ../functions/functions.cpp \
    ../functions/mpd_cli.cpp \
    ../iDomStatus/idomstatus.cpp \
    ../KEY/key.cpp \
    ../LCD_c/lcd_c.cpp \
    ../logger/logger.cc \
    ../menu_tree/main.cpp \
    ../menu_tree/menu_tree.cpp \
    ../RADIO_433_eq/radio_433_eq.cpp \
    ../RADIO_433_eq/radio_button.cpp \
    ../TASKER/tasker.cpp \
    ../THERMOMETER_CONTAINER/thermometer_container.cpp \
    ../iDom_server_OOP.cpp \
    ../../libs/alarm clock/alarmClockTEST/alarm_clock.cpp \
    ../../libs/android_functions/android_interface/android_interface.cpp \
    ../../libs/android_functions/androidhelper_cyniu.cpp \
    ../../libs/config_files/config_files.cpp \
    ../../libs/config_parser/parser.cpp \
    ../../libs/emoji/emoji.cpp \
    ../../libs/event_counter_test/event_counters/event/event_command.cpp \
    ../../libs/event_counter_test/event_counters/event/event_mpd.cpp \
    ../../libs/event_counter_test/event_counters/event/event_pilot.cpp \
    ../../libs/event_counter_test/event_counters/event/event_unknown.cpp \
    ../../libs/event_counter_test/event_counters/event/new_connect_event.cpp \
    ../../libs/event_counter_test/event_counters/event_counters.cpp \
    ../../libs/event_counter_test/event_counters/event_counters_handler.cpp \
    ../../libs/facebookAPI/facebookAPI.cpp \
    ../../libs/fann_lib/examples/xor_sample.cpp \
    ../../libs/sgvTEST/thermometerSVG/thermometer.cpp \
    ../../libs/sgvTEST/eye.cpp \
    ../../libs/sgvTEST/main.cpp \
    ../../libs/sunrise-sunset/sunriseset.cpp \
    ../../libs/viberAPI/viber_api.cpp \
    ../../libs/fann_lib/examples/cascade_train.c \
    ../../libs/fann_lib/examples/momentums.c \
    ../../libs/fann_lib/examples/mushroom.c \
    ../../libs/fann_lib/examples/robot.c \
    ../../libs/fann_lib/examples/scaling_test.c \
    ../../libs/fann_lib/examples/scaling_train.c \
    ../../libs/fann_lib/examples/simple_test.c \
    ../../libs/fann_lib/examples/simple_train.c \
    ../../libs/fann_lib/examples/steepness_train.c \
    ../../libs/fann_lib/examples/xor_test.c \
    ../../libs/fann_lib/examples/xor_train.c \
    ../../libs/fann_lib/src/doublefann.c \
    ../../libs/fann_lib/src/fann.c \
    ../../libs/fann_lib/src/fann_cascade.c \
    ../../libs/fann_lib/src/fann_error.c \
    ../../libs/fann_lib/src/fann_io.c \
    ../../libs/fann_lib/src/fann_train.c \
    ../../libs/fann_lib/src/fann_train_data.c \
    ../../libs/fann_lib/src/fixedfann.c \
    ../../libs/fann_lib/src/floatfann.c

HEADERS += \
    ../../libs/useful/useful.h \
    idomtools.h \
    idomtools_useful.h \
    ../433MHz/rc_433mhz.h \
    ../blockQueue/blockqueue.h \
    ../c_connection/c_connection.h \
    ../c_irda_logic/c_irda_logic.h \
    ../c_master_irda/master_irda.h \
    ../command/commandClass/command_433mhz.h \
    ../command/commandClass/command_ardu.h \
    ../command/commandClass/command_big.h \
    ../command/commandClass/command_clock.h \
    ../command/commandClass/command_cmd.h \
    ../command/commandClass/command_event.h \
    ../command/commandClass/command_hello.h \
    ../command/commandClass/command_help.h \
    ../command/commandClass/command_idom.h \
    ../command/commandClass/command_ip.h \
    ../command/commandClass/command_log.h \
    ../command/commandClass/command_mpd.h \
    ../command/commandClass/command_ok.h \
    ../command/commandClass/command_put.h \
    ../command/commandClass/command_show.h \
    ../command/commandClass/command_sleep.h \
    ../command/commandClass/command_state.h \
    ../command/commandClass/command_stop.h \
    ../command/commandClass/command_uptime.h \
    ../command/commandClass/commandexit.h \
    ../command/commandClass/commandrs232.h \
    ../command/commandClass/commandtest.h \
    ../command/command.h \
    ../command/commandhandler.h \
    ../command/commandhandlerroot.h \
    ../command/commandhandlerrs232.h \
    ../CRON/cron.hpp \
    ../files_tree/files_tree.h \
    ../functions/functions.h \
    ../functions/mpd_cli.h \
    ../iDomStatus/idomstatus.h \
    ../KEY/key.h \
    ../LCD_c/lcd_c.h \
    ../logger/logger.hpp \
    ../menu_tree/menu_tree.h \
    ../RADIO_433_eq/radio_433_eq.h \
    ../RADIO_433_eq/radio_button.h \
    ../TASKER/tasker.h \
    ../THERMOMETER_CONTAINER/thermometer_container.h \
    ../iDom_server_OOP.h \
    ../../libs/alarm clock/alarmClockTEST/alarm_clock.h \
    ../../libs/android_functions/android_interface/android_interface.h \
    ../../libs/android_functions/androidhelper_cyniu.h \
    ../../libs/config_files/config_files.h \
    ../../libs/config_parser/parser.hpp \
    ../../libs/emoji/emoji.h \
    ../../libs/event_counter_test/event_counters/event/event_command.h \
    ../../libs/event_counter_test/event_counters/event/event_mpd.h \
    ../../libs/event_counter_test/event_counters/event/event_pilot.h \
    ../../libs/event_counter_test/event_counters/event/event_unknown.h \
    ../../libs/event_counter_test/event_counters/event/new_connect_event.h \
    ../../libs/event_counter_test/event_counters/event_counters.h \
    ../../libs/event_counter_test/event_counters/event_counters_handler.h \
    ../../libs/facebookAPI/facebookAPI.h \
    ../../libs/fann_lib/src/include/compat_time.h \
    ../../libs/fann_lib/src/include/config.h \
    ../../libs/fann_lib/src/include/doublefann.h \
    ../../libs/fann_lib/src/include/fann.h \
    ../../libs/fann_lib/src/include/fann_activation.h \
    ../../libs/fann_lib/src/include/fann_cascade.h \
    ../../libs/fann_lib/src/include/fann_cpp.h \
    ../../libs/fann_lib/src/include/fann_data.h \
    ../../libs/fann_lib/src/include/fann_error.h \
    ../../libs/fann_lib/src/include/fann_internal.h \
    ../../libs/fann_lib/src/include/fann_io.h \
    ../../libs/fann_lib/src/include/fann_train.h \
    ../../libs/fann_lib/src/include/fixedfann.h \
    ../../libs/fann_lib/src/include/floatfann.h \
    ../../libs/sgvTEST/thermometerSVG/thermometer.h \
    ../../libs/sgvTEST/eye.h \
    ../../libs/Statistic/statistic.h \
    ../../libs/sunrise-sunset/sunriseset.h \
    ../../libs/viberAPI/viber_api.h
