name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
  #  - name: Install CMAKE GIT and libs
   #   run: 'sudo apt-get update && sudo apt-get install -y cmake git libmpd-dev curl libcurl4-openssl-dev libmpdclient-dev libgtest-dev google-mock libgmock-dev libmosquitto-dev libi2c-dev'
    - name: pwd
      run: pwd
    - name: ls
      run: 'cd / && ls -lah'
    - name: cd iDom_server_OOP
      run: cd iDom_server_OOP
    - name: cmake
      run: cmake .
    - name: make 
      run: make -j4
