name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true        # Pobieranie submodułów
        fetch-depth: 0  
    - name: Install CMAKE GIT and libs
      run: 'sudo apt-get update && sudo apt-get install -y cmake git libmpd-dev curl libcurl4-openssl-dev libmpdclient-dev libgtest-dev google-mock libgmock-dev libmosquitto-dev libi2c-dev'
    - name: pwd
      run: pwd
    - name: ls
      run: ls
    - name: cd iDom_server_OOP
      run: cd iDom_server_OOP
    - name: pwd
      run: pwd
    - name: cmake iDom app
      run: cmake ./iDom_server_OOP
   # - name: make iDom app
  #    run: make -j4
    - name: cmake iDom test
      run: cmake .
      working-directory: ./iDom_server_OOP/test/iDom_TESTs-CMAKE
    - name: make iDom test
      run: make -j4
      working-directory: ./iDom_server_OOP/test/iDom_TESTs-CMAKE
    - name: make iDom test ls
      run: ls -lah
      working-directory: ./iDom_server_OOP/test/iDom_TESTs-CMAKE
    - name: add ramdisk and  tty
      run: 'mkdir -p /mnt/ramdisk && touch /dev/tty0'
    - name: run test
      run: ./iDom_TESTs-CMAKE
      working-directory: ./iDom_server_OOP/test/iDom_TESTs-CMAKE
    - name: show logs
      run: cat /mnt/ramdisk/iDom_log_BT.log
